apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helloworld-v1.yaml
  - helloworld-namespace.yaml
  - helloworld-istio.yaml
  - helloworld-v2.yaml
  - helloworld-hpa.yaml
  - helloworld-nginx.yaml